# Target specific macros
TARGET = BRO_client
TARGET_SOURCES := \
	BRO_spam_client.c \
	BRO_spam_fists.c 
TOPPERS_OSEK_OIL_SOURCE := ./BRO_spam_client.oil

O_PATH ?= build

include ../../nxtOSEK/ecrobot/ecrobot.mak

