# Target specific macros
TARGET = usb_client

TARGET_CPP_SOURCES = usb_client.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./usb_client.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../../nxtOSEK/ecrobot/ecrobot++.mak
